version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: ./nginx/DockerFile
    depends_on:
      - app
    ports:
      - 80:80
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  app:
    build:   
      context: .
      dockerfile: ./DockerFile    
    depends_on:
      - db
